spring:
  profiles:
    active: dev
       
---
spring:
  profiles: dev
  application:
      name: dscloud-config-dev
      
---
spring:
  profiles: test
  application:
      name: dscloud-config-test
