spring:
  profiles:
    active:
      - dev
---
spring:
  profile: dev
    application:
      name: dacloud-config-dev
---
spring:
  profile: test
    application:
      name: dacloud-config-test

# 请保存UTF-8格式

