spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.dasong.api.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profile: dev
  application:
     name: dscloud-config-dept-client
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://10.91.31.34:3306/share?useUnicode=true&useSSL=false&characterEncoding=UTF8
     username: root
     password: root
     dbcp2: #启用dbcp2配置
       min-idle: 5 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,
       initial-size: 5 #初始化连接数量
       max-total: 5
       max-wait-millis: 20
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
        # 自定义服务名称
    instance:
      instance-id: dept-8001.com
      # 访问路径可以显示ip地址
      prefer-ip-address: true
