spring:
  profiles: dev
    active:
    - dev
---
server:
  port: 8001
  
spring:
  profiles: dev
  application:
     name: dscloud-config-dept-client
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/cloud-1?useUnicode=true&useSSL=false&characterEncoding=UTF8
     username: root
     password: 123456
     dbcp2: #启用dbcp2配置
       min-idle: 5 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,
       initial-size: 5 #初始化连接数量
       max-total: 5
       max-wait-millis: 20

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责是维护服务实例，并不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
        # 自定义服务名称
    instance-id: dept-8001.com
    # 访问路径可以显示ip地址
    prefer-ip-address: true
  
 ---
 server:
  port: 8001
  
spring:
  profiles: test
  application:
     name: dscloud-config-dept-client
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/cloud-2?useUnicode=true&useSSL=false&characterEncoding=UTF8
     username: root
     password: 123456
     dbcp2: #启用dbcp2配置
       min-idle: 5 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,
       initial-size: 5 #初始化连接数量
       max-total: 5
       max-wait-millis: 20

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责是维护服务实例，并不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
        # 自定义服务名称
    instance-id: dept-8001.com
    # 访问路径可以显示ip地址
    prefer-ip-address: true
